### ISSUE TITLE
Can't build due to missing dependency on ndt_feature

### ISSUE THREAD

**Issue by martinmagnusson** [MalcolmMielle/Auto-Complete-Graph#1]
Using 7fa7b62, I have trouble building this package. I have `perception_oru` from `https://github.com/OrebroUniversity/perception_oru.git` which includes a package `ndt_feature_reg` but not `ndt_feature`. Which version/branch of `perception_oru` does this package depend on?

**Comment by MalcolmMielle** [comment]
`ndt_feature` is a different package that is outside of `perception_oru`. You can find it [here](https://github.com/MalcolmMielle/ndt_feature_graph).
This package should work with the latest indigo/knetic branch of `perception_oru`
