### ISSUE TITLE
Issues on the code in `graph_map_publisher_localization.cpp`

### ISSUE THREAD

**Issue by ljjTYJR** [MalcolmMielle/Auto-Complete-Graph#12]
I found some problems when running the code, I am not sure if It is my problem or the code.
In the code:
https://github.com/MalcolmMielle/Auto-Complete-Graph/blob/ffe7b0df929d8a341fc595d1391d6a623e7f86c3/src/Localization/graph_map_publisher_localization.cpp?#L835-L861

In the line
https://github.com/MalcolmMielle/Auto-Complete-Graph/blob/ffe7b0df929d8a341fc595d1391d6a623e7f86c3/src/Localization/graph_map_publisher_localization.cpp?#L859

Is it correct to transform the `cloud` using `sensorpose2`? Since `sensorpose2` is the pose of the robot_base.

From the visualization of rviz, it seems that it should be
```c++
pcl::transformPointCloud(transformed_cloud, transformed_cloud2, sensorpose2); 
```

I am not sure whether there exists a problem... Maybe there are some other reasons?

Best

**Comment by MalcolmMielle** [comment]
I think you are right. Probably in my experiment the sensor position and the base where at the same place?

Feel free to send a PR to correct this error :)

**Comment by ljjTYJR** [comment]
#14
